[platformio]
default_envs = giga-hil
src_dir = src
include_dir = include

[env:giga-hil]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../lib
build_flags =
  -Iinclude

[env:giga-hil-placeholder]
extends = env:giga-hil
build_flags =
  ${env:giga-hil.build_flags}
  -DHIL_PLACEHOLDER_CONFIG
