[platformio]
default_envs = giga-epaper-hil
src_dir = src

[env:giga-epaper-hil]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../lib
lib_deps =
  zinggjm/GxEPD2 @ 1.6.9
