[platformio]
src_dir = .

[env:uno-r4-wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
upload_port = /dev/cu.usbmodemF412FA9B73FC2
monitor_port = /dev/cu.usbmodemF412FA9B73FC2
monitor_speed = 115200
