[platformio]
default_envs = opta-hil
src_dir = src

[env:opta-hil]
platform = ststm32
board = opta
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../lib
lib_deps =
  arduino-libraries/ArduinoRS485
